name: QuickShopForm
version: '${project.version}'
main: ren.rymc.quickshopform.QuickShopForm
api-version: 1.13
depend: [ floodgate, QuickShop ]
authors: [ RENaa_FD ]
description: 快捷商店Form菜单支持
website: https://rymc.ren/
