name: QuickShopForm
version: '${project.version}'
main: ltd.rymc.form.quickshop.QuickShopForm
api-version: 1.18
depend: [ floodgate ]
softdepend: [ QuickShop, QuickShop-Hikari ]
authors: [ RENaa_FD ]
description: 快捷商店Form菜单支持
website: https://rymc.ltd/
