name: QuickShopForm 自动构建

on:
  push:
    branches:
      - hikari
  pull_request:
    branches:
      - hikari

jobs:
  build:

    if: contains(github.event.head_commit.message, '[构建跳过]') == false
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: QuickShopForm-Hikari
        path: target/QuickShopForm-Hikari.jar
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      if: success()
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "hikari-dev"
        prerelease: false
        title: "QuickShopForm-Hikari 自动构建版本"
        files: |
          target/QuickShopForm-Hikari.jar
        
